[project]
name = "library-rest"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "IkerOwO", email = "162556194+IkerOwO@users.noreply.github.com" }
]
requires-python = ">=3.13"
dependencies = [
    "asyncmy>=0.2.15",
    "bcrypt>=5.0.0",
    "fastapi>=0.141.1",
    "fastapi-users[sqlalchemy]>=15.0.5",
    "mysql-connector-python>=26.7.0",
    "pydantic>=2.13.5",
    "python-dotenv>=1.2.3",
    "sqlalchemy[asyncio]>=2.0,<2.1",
]

[project.scripts]
library-rest = "library_rest:main"

[build-system]
requires = ["uv_build>=0.12.19,<0.13.0"]
build-backend = "uv_build"
